name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Vite App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ~/auth-flow-front-end 
            git pull origin main
            git config --global --add safe.directory /home/ubuntu/auth-flow-front-end
            sudo chown -R $USER:$USER /home/ubuntu/auth-flow-front-end
            npm install
            npm run build
            sudo rm -rf /var/www/your-frontend/*
            sudo cp -r dist/* /var/www/your-frontend/
            sudo chown -R www-data:www-data /var/www/your-frontend
            sudo systemctl reload nginx
            echo "✅ Deployment completed."
          EOF
